# Generated by Django 2.0 on 2019-06-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190603_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
